import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { supabaseAdmin } from '@/lib/supabase'
import { sendEmail } from '@/lib/email'
import { aiRouteRateLimit } from '@/lib/ratelimit'

const ReportRequestSchema = z.object({
  auditId: z.string().min(1, 'auditId is required'),
  email: z.string().email('Must be a valid email'),
})

function scoreLabel(score: number): string {
  if (score >= 90) return 'Excellent'
  if (score >= 70) return 'Good — minor improvements needed'
  if (score >= 50) return 'Needs work — several issues found'
  return 'Poor — significant improvements required'
}

function scoreColor(score: number): string {
  if (score >= 80) return '#22c55e'
  if (score >= 50) return '#f59e0b'
  return '#ef4444'
}

function scoreRow(label: string, score: number): string {
  const color = scoreColor(score)
  const interpretation = scoreLabel(score)
  return `
    <tr>
      <td style="padding:14px 16px;border-bottom:1px solid #e5e7eb;font-weight:600;color:#374151">${label}</td>
      <td style="padding:14px 16px;border-bottom:1px solid #e5e7eb;text-align:center">
        <span style="font-size:22px;font-weight:700;color:${color}">${score}</span>
        <span style="font-size:12px;color:#9ca3af">/100</span>
      </td>
      <td style="padding:14px 16px;border-bottom:1px solid #e5e7eb;color:${color};font-size:14px">${interpretation}</td>
    </tr>`
}

function buildReportHtml(audit: {
  url: string
  created_at: string
  score_performance: number
  score_seo: number
  score_accessibility: number
  score_best_practices: number
  has_ssl: boolean
  is_mobile_friendly: boolean
  ai_summary: string | null
}): string {
  const auditDate = new Date(audit.created_at).toLocaleDateString('en-GB', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })

  const sslHtml = audit.has_ssl
    ? `<span style="color:#22c55e;font-weight:600">&#10003; Secure (HTTPS enabled)</span>`
    : `<span style="color:#ef4444;font-weight:600">&#10007; Not secure — no SSL certificate detected</span>`

  const mobileHtml = audit.is_mobile_friendly
    ? `<span style="color:#22c55e;font-weight:600">&#10003; Mobile friendly</span>`
    : `<span style="color:#ef4444;font-weight:600">&#10007; Not fully mobile friendly</span>`

  const aiSectionHtml = audit.ai_summary
    ? `<div style="margin-top:32px">
        <h2 style="margin:0 0 12px;font-size:18px;color:#1f2937;border-bottom:2px solid #6c3cff;padding-bottom:8px">AI Analysis</h2>
        <div style="background:#f5f3ff;border-left:4px solid #6c3cff;padding:16px 20px;border-radius:4px;color:#374151;line-height:1.7;font-size:15px">${audit.ai_summary}</div>
      </div>`
    : ''

  return `
    <div style="font-size:15px;color:#374151;line-height:1.6">

      <div style="background:#6c3cff;margin:-30px -30px 28px;padding:28px 30px">
        <h1 style="margin:0 0 4px;color:#fff;font-size:24px;font-weight:700">Website Audit Report</h1>
        <p style="margin:0;color:#c4b5fd;font-size:14px">Generated by Zypflow</p>
      </div>

      <div style="background:#f9fafb;border-radius:8px;padding:16px 20px;margin-bottom:24px">
        <p style="margin:0 0 4px"><strong>Website:</strong> <a href="${audit.url}" style="color:#6c3cff;text-decoration:none">${audit.url}</a></p>
        <p style="margin:0"><strong>Audit date:</strong> ${auditDate}</p>
      </div>

      <h2 style="margin:0 0 12px;font-size:18px;color:#1f2937;border-bottom:2px solid #6c3cff;padding-bottom:8px">Performance Scores</h2>
      <table style="width:100%;border-collapse:collapse;margin-bottom:8px">
        <thead>
          <tr style="background:#f3f4f6">
            <th style="padding:10px 16px;text-align:left;font-size:13px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:0.05em">Category</th>
            <th style="padding:10px 16px;text-align:center;font-size:13px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:0.05em">Score</th>
            <th style="padding:10px 16px;text-align:left;font-size:13px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:0.05em">What it means</th>
          </tr>
        </thead>
        <tbody>
          ${scoreRow('Performance', audit.score_performance)}
          ${scoreRow('SEO', audit.score_seo)}
          ${scoreRow('Accessibility', audit.score_accessibility)}
          ${scoreRow('Best Practices', audit.score_best_practices)}
        </tbody>
      </table>

      <div style="margin-top:28px">
        <h2 style="margin:0 0 12px;font-size:18px;color:#1f2937;border-bottom:2px solid #6c3cff;padding-bottom:8px">Technical Checks</h2>
        <div style="background:#f9fafb;border-radius:8px;padding:16px 20px">
          <p style="margin:0 0 10px;font-size:15px"><strong>SSL Certificate:</strong>&nbsp; ${sslHtml}</p>
          <p style="margin:0;font-size:15px"><strong>Mobile Friendly:</strong>&nbsp; ${mobileHtml}</p>
        </div>
      </div>

      ${aiSectionHtml}

      <div style="margin-top:36px;background:#f5f3ff;border-radius:10px;padding:24px;text-align:center">
        <p style="margin:0 0 8px;font-size:17px;font-weight:600;color:#1f2937">Want to improve these scores?</p>
        <p style="margin:0 0 16px;color:#6b7280;font-size:14px">Zypflow can help automate your business growth — from faster websites to better SEO and more leads.</p>
        <a href="https://app.zypflow.com/signup" style="display:inline-block;background:#6c3cff;color:#fff;padding:12px 28px;border-radius:8px;text-decoration:none;font-weight:600;font-size:15px">Start Your Free Trial at app.zypflow.com/signup</a>
      </div>

    </div>`
}

/**
 * POST /api/audit/report
 * Looks up an audit by ID, emails an HTML audit report to the provided address.
 */
export async function POST(req: NextRequest) {
  // 1. Rate limit by IP
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'unknown'
  const { success: rateLimitOk } = await aiRouteRateLimit.limit(`audit-report:${ip}`)
  if (!rateLimitOk) {
    return NextResponse.json({ error: 'Rate limit exceeded. Try again later.' }, { status: 429 })
  }

  // 2. Parse + validate body
  let body: unknown
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const parsed = ReportRequestSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.errors[0]?.message ?? 'Invalid request' },
      { status: 400 }
    )
  }

  const { auditId, email } = parsed.data

  // 3. Look up the audit
  const { data: audit, error: fetchError } = await supabaseAdmin
    .from('audits')
    .select('id, url, email, created_at, score_performance, score_seo, score_accessibility, score_best_practices, has_ssl, is_mobile_friendly, ai_summary')
    .eq('id', auditId)
    .maybeSingle()

  if (fetchError) {
    console.error('Audit fetch error:', fetchError)
    return NextResponse.json({ error: 'Failed to retrieve audit.' }, { status: 500 })
  }

  if (!audit) {
    return NextResponse.json({ error: 'Audit not found.' }, { status: 404 })
  }

  // 4. Store email on the audit record if not already set
  if (!audit.email) {
    const { error: updateError } = await supabaseAdmin
      .from('audits')
      .update({ email })
      .eq('id', auditId)

    if (updateError) {
      console.error('Audit email update error:', updateError)
      // Non-fatal — proceed to send the report anyway
    }
  }

  // 5. Build report HTML
  const reportHtml = buildReportHtml({
    url: audit.url,
    created_at: audit.created_at,
    score_performance: audit.score_performance ?? 0,
    score_seo: audit.score_seo ?? 0,
    score_accessibility: audit.score_accessibility ?? 0,
    score_best_practices: audit.score_best_practices ?? 0,
    has_ssl: audit.has_ssl ?? false,
    is_mobile_friendly: audit.is_mobile_friendly ?? false,
    ai_summary: audit.ai_summary ?? null,
  })

  // 6. Send the report email
  const { error: emailError } = await sendEmail({
    to: email,
    subject: `Website Audit Report: ${audit.url}`,
    html: reportHtml,
  })

  if (emailError) {
    console.error('Audit report email error:', emailError)
    return NextResponse.json({ error: 'Failed to send report email.' }, { status: 500 })
  }

  return NextResponse.json({ success: true, emailSent: true })
}
